version: '3'
services:
  mysql:
    image: mysql:latest
    hostname: root
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
      - "33060:33060"

  mainservice:
    build:
      context: ../mainservice/build/libs
      dockerfile: ../../../script/mainservice/Dockerfile
    depends_on:
      - eureka
    ports:
      - "8080:8080"
  microservice:
    build:
      context: ../microservice/build/libs
      dockerfile: ../../../script/microservice/Dockerfile
    depends_on:
      - eureka
    ports:
      - "8081:8081"
  gateway:
    build:
      context: ../gateway/build/libs
      dockerfile: ../../../script/gateway/Dockerfile
    depends_on:
      - mainservice
      - microservice
      - eureka
    ports:
      - "8082:8082"
  eureka:
    build:
      context: ../eureka/build/libs
      dockerfile: ../../../script/eureka/Dockerfile
    depends_on:
      - mysql
    ports:
      - "8083:8083"